"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_latte"

format = """
[](lavender)\
$directory\
[ ](fg:lavender bg:sky)\
$git_branch\
$git_status\
[ ](fg:sky bg:sapphire)\
$golang\
$kubernetes\
$nodejs\
[ ](fg:sapphire)\
$os \
$hostname\
$cmd_duration $time\
$character$status
 󰧚 \
"""

[time]
disabled = false
format = '[ $time]($style) '
time_format = "%H:%M"
style = "fg:text"

[directory]
truncation_length = 3
truncation_symbol = '…/'
style = "fg:base bg:lavender"
format = "[$path ]($style)"

[git_branch]
symbol = ""
style = "bg:sky fg:base"
format = '[$symbol $branch]($style)'

[git_status]
style = "bg:sky fg:base"
format = '[$all_status$ahead_behind ]($style)'

[golang]
style = "fg:base bg:sapphire"
version_format = '${major}.${minor}'
not_capable_style = 'fg:red bg:sapphire'
format = '[󰟓 $version ]($style)'

[character]
error_symbol = "[](fg:red)"
success_symbol = "[](fg:green)"
disabled = false

[status]
disabled = false
style = 'fg:red'
format = "[$int]($style)"

[kubernetes]
style = "fg:base bg:sapphire"
format = '[󱃾 $context ]($style)'
disabled = false
detect_files = ['k8s']

[cmd_duration]
min_time = 500
format = '[ 󱦟$duration](yellow)'

[os]
disabled = false

[os.symbols]
Windows = "[ Windows](fg:sky)"
Linux = "[ Linux](fg:text)"
Macos = "[ MacOS](fg:text)"
Fedora = "[ Fedora](fg:sky)"

[nodejs]
style = "fg:base bg:sapphire"
format = '[󰎙 $version ]($style)'
version_format = '${major}.${minor}'

[hostname]
ssh_only = false
disabled = false
format = "[ $hostname]($style)"
style = "fg:teal"

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"

[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
